name: My first workflow
on:
  push:
    branches:
      - main

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello, world! from GitHub Actions"

      - name: List all files
        run: ls -la