name: My first workflow
on:
  push:
    branches:
      - main

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Say Hello
        run: echo "Hello, world! from GitHub Actions"

      - name: List all files
        run: ls -la

      - name: make folder
        run: mkdir -p victor
      
      - name: Create a file
        run: echo "This is a test file." > victor/test.txt

      - name: PHP versions
        run: php -v

      - name: Server USername
        run: echo "Server Username: ${{ secrets.USERNAME }}"

      - name: Server IP
        run: echo "Server IP: ${{ secrets.SERVER_IP }}"

  