name: My first workflow
on:
  push:
    branches:
      - main

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Say Hello
        run: echo "Hello, world! from GitHub Actions"

      - name: List all files
        run: ls -la

      - name: make folder
        run: msohsodfvhcsdflkbsfdklvjsdfcdsv
      
      - name: Create a file
        run: echo "This is a test file." > victor/test.txt

      - name: PHP version
        run: php -v

      - name: Connect to Server
        run: ssh ${{secrets.USERNAME}}@${{secrets.SERVER_IP}} "echo 'Connected to server!'"


      

  